# Wire up travis
language: python
sudo: false

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3"

matrix:
    include:
    - python: "2.7"
      env: TOXENV=cover

install:
  - travis_retry pip install tox-travis

script:
  - travis_retry tox

notifications:
  email:
    - pyramid-checkins@lists.repoze.org
